### ISSUE TITLE
Hello world tutorial

### ISSUE THREAD

**Issue by lankinenxyz** [flatironinstitute/reactopya#1]
It would be super helpful to understand this better by seeing some example. Simple "hello world" project.

**Comment by magland** [comment]
Hi @RealLankinen , thanks for the request. I am putting this on my todo list and will have a basic hello world example soon.

**Comment by magland** [comment]
@RealLankinen, I have created an example project here:
https://github.com/flatironinstitute/reactopya/tree/master/example_projects/hello_world

The README.md has a tutorial for reproducing the example.

Certainly the tutorial may be expanded, so if you ask questions I can add answers there over time.

**Comment by lankinenxyz** [comment]
The part you wrote works perfectly! But I feel like you could go a little bit further with this. How to publish the widget on PyPi? I think the great place to end the example could be to show that it also works in Jupyter Lab not just pop up browser.

**Comment by lankinenxyz** [comment]
Also I just realized what is the idea of needing to manually add widget info to dev_widget.json? Couldn't you just add it automatically every time someone runs reactopya new-widget?

**Comment by magland** [comment]
The idea is that the project would typically have many widgets, and usually
you are developing only one widget at a time. But I agree the manual step
is a bit cumbersome and not obvious. Will need to think further about this.

**Comment by lankinenxyz** [comment]
I believe that I now published the project successfully on PyPi by running following commands:
`cd generated/HelloWorld`
`python setup.py sdist`
`twine upload dist/*`
One thing I notice was that it didn't took the documentation from docs folder. I will test if I get it work on Jupyter Notebook.

**Comment by magland** [comment]
I am creating the jupyter instructions now in the tutorial.

Also, there is a `reactopya publish-pypi` command.

**Comment by magland** [comment]
Tutorial has been updated to include jupyter usage and publish pypi.

Perhaps the publish pypi does not include the docs as it should. That's probably a simple fix, but NOT on my todo list at the moment.

**Comment by lankinenxyz** [comment]
Okay I totally understand that. 

I tested the tutorial and got this problem after running `reactopya publish-pypi`

```
Traceback (most recent call last):
  File "/home/user/anaconda3/bin/reactopya", line 643, in <module>
    main()
  File "/home/user/anaconda3/bin/reactopya", line 115, in main
    commands_by_name[command](config, args=args)
  File "/home/user/anaconda3/bin/reactopya", line 348, in _publish_pypi
    _install_all(config, args)
  File "/home/user/anaconda3/bin/reactopya", line 286, in _install_all
    _install_jupyter(config, args)
NameError: name '_install_jupyter' is not defined
```

**Comment by magland** [comment]
I recently fixed that bug, but I think did not push a new version (of reactopya) to pypi. I just pushed 0.10.6, so you can pip upgrade to that and I think it should work.

**Comment by lankinenxyz** [comment]
Amazing! It worked. Thank you for quickly fixing this problem.
